### ISSUE TITLE
Combat log spell IDs are empty

### ISSUE THREAD

**Issue by AgentFX** [Jods-GH/DungeonAuraTools#121]
### Description

Weakauras using combat log trigger get imported/updated without Spell ID.
Might be due to a weak aura update, not sure when they updated the combat log triggers but every weakaura using combat log trigger didn't come with a spell ID. Only checked a around 5 auras.

### WeakAuras Version

5.8.0

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.4.7

### Tested with only WeakAuras and DungeonAuraTools

- [ ] Yes
- [X] No

### Reproduction Steps

1. Import Dat weakauras

### Saved Variables

[DungeonAuraTools.zip](https://github.com/Jods-GH/DungeonAuraTools/files/12849555/DungeonAuraTools.zip)

### Screenshots

![image](https://github.com/Jods-GH/DungeonAuraTools/assets/38831914/af037ae2-3d90-4d01-9327-9e48ccf1ebc4)

**Comment by Jodsderechte** [comment]
yeah that looks like it's due to the wa update and i missed it. Thanks for reporting i'll fix that asap. If you find any other missing data let me know i might have missed even more things

**Comment by AgentFX** [comment]
Will do if I find anything new.
