### ISSUE TITLE
Warlords of Draenor group only "import as copy" can't update

### ISSUE THREAD

**Issue by AgentFX** [Jods-GH/DungeonAuraTools#124]
### Description

I can update all the all the other Expansions just as usual, just warlords of draenor doesn't give me the option to update, only import as copy. I already tried deleting the WoD group and importing it again and then updating it, same issue. Can only copy not update.

I have a screenshot attached of my loaded WoD Dungeons, it's just everbloom so my guess would be an aura in there.

Might just be a problem with me already loading the Dungeon even tho it's not really out yet and you're probably not done, just a note in case it might help :) feel free to close the issue if that's the case.

Haven't tried it with my friends yet, I'm gonna tell them to update it when they're back from work and update this post if they have the same issue.

### WeakAuras Version

5.8.1

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.4.8

### Tested with only WeakAuras and DungeonAuraTools

- [ ] Yes
- [X] No

### Reproduction Steps

1. Import WoD weakaura
2. update WoD weakaura
3. Can only import not update

### Saved Variables

[DungeonAuraTools.zip](https://github.com/Jods-GH/DungeonAuraTools/files/12858906/DungeonAuraTools.zip)

### Screenshots

![image](https://github.com/Jods-GH/DungeonAuraTools/assets/38831914/9108da0e-a5f2-4e7a-ba2b-cfc476ff90f4)
![image](https://github.com/Jods-GH/DungeonAuraTools/assets/38831914/1f55048c-f2d1-4874-8f91-f30e973d9a56)

**Comment by AgentFX** [comment]
Just happened again while troubleshooting another bug without me changing anything from one relog to another, so it's a bit harder to replicate. Gonna test this a bit more before I reopen the ticket

**Comment by AgentFX** [comment]
Alright managed to reproduce it with a friend.
1. Delete WoD Group
2. Log out (did this for safety, not sure if necesary )
3. Send Auras to WA (import WoD Auras, specifically Everbloom)
4. Log out (this is required)
5. Send Auras to WA, WoD auras can only be imported not updated
6. Reproduced

**Comment by AgentFX** [comment]
If you want to message me directly I can join your discord or you can message me. Discord username: agentfx

**Comment by Jodsderechte** [comment]
so does this happen only with everbloom? And did you actually change anything before send auras to wa? if the table is exactly the same it just gives you the option to import cause there is nothing to update

**Comment by Jodsderechte** [comment]
I have the same thing happening with other groups aswell it's not specific to wod for me
