### ISSUE TITLE
Align Direction in grow specific options doesn't change anything.

### ISSUE THREAD

**Issue by AgentFX** [Jods-GH/DungeonAuraTools#125]
### Description

When I change the align direction in DaT it doesn't get imported to weak auras. The anchor is greyed out in weak auras so it might be a weak auras issue instead of DaT.

### WeakAuras Version

5.8.1

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.4.8

### Tested with only WeakAuras and DungeonAuraTools

- [ ] Yes
- [X] No

### Reproduction Steps

1. Change Align Direction in General settings
2. Import to weak auras

### Saved Variables

[DungeonAuraTools.zip](https://github.com/Jods-GH/DungeonAuraTools/files/12859315/DungeonAuraTools.zip)

### Last Good Version

5.8.1

### Screenshots

![image](https://github.com/Jods-GH/DungeonAuraTools/assets/38831914/d42a8483-514f-4439-840c-23bc919658df)

**Comment by AgentFX** [comment]
The anchor is on the left because the group was created before when the bug didn't exists. New groups get their anchor in the center.

**Comment by Jodsderechte** [comment]
hm maybe thats another issue due to the latest wa change to the position changes i'll do some investigating on this tomorrow

**Comment by Jodsderechte** [comment]
After some more investigation the align option is not what you screenshotted. It's the option just above that is called "Align" however i did find an unrelated bug that i fixed
