### ISSUE TITLE
Changing certain auras to bars sends an update message in chat on every log in

### ISSUE THREAD

**Issue by AgentFX** [Jods-GH/DungeonAuraTools#126]
### Description

Changing some auras (not all) sends me an update message on every log in, same happens with my friend. Aura in question is the Incorporeal aura. Reloading after log in doesn't send the message again, just on initial log in.
Afflicted doesn't have the same behaviour, even when changed to Bar instead of Icon.

I have a few DotI auras changed to bars as well, one of those also sends the message, gonna check which one and comment it. Maybe it helps with troubleshooting

### WeakAuras Version

5.8.1

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.4.8

### Tested with only WeakAuras and DungeonAuraTools

- [ ] Yes
- [X] No

### Reproduction Steps

1. Change Incorporeal Aura to a Bar in Dat
2. send aura to wa
3. log out
4. log in
5. chat message appears on every log in and disappears after reloading

### Saved Variables

[DungeonAuraTools.zip](https://github.com/Jods-GH/DungeonAuraTools/files/12859528/DungeonAuraTools.zip)

### Screenshots

![image](https://github.com/Jods-GH/DungeonAuraTools/assets/38831914/c3cd4908-711e-41d8-88f3-edc7898603b5)

**Comment by AgentFX** [comment]
The "corrosion" spell from Blight of Galakrond in Dawn of the Infinites also gives you a message on every log in if you change it into a bar instead of an icon.

**Comment by Jodsderechte** [comment]
You are the first one to deeply test the bar changing type. Might be something relaated to how updates are detected
