### ISSUE TITLE
Update Check Error

### ISSUE THREAD

**Issue by xSaltyx** [Jods-GH/DungeonAuraTools#136]
### Description

14x DungeonAuraTools/Util/UpdateCheck.lua:229: Warning Internal Wa Version does not match Please alert the Author found: 71 expected: 70
[string "=[C]"]: in function `assert'
[string "@DungeonAuraTools/Util/UpdateCheck.lua"]:229: in function `adjustAuras'
[string "@DungeonAuraTools/Util/UpdateCheck.lua"]:96: in function `CheckIfAuraUpdates'
[string "@DungeonAuraTools/Main.lua"]:102: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = false
(*temporary) = "Warning Internal Wa Version does not match Please alert the Author found: 71 expected: 70"

### WeakAuras Version

5.12.5

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.56

### Tested with only WeakAuras and DungeonAuraTools

- [ ] Yes
- [ ] No

### Lua Error

14x DungeonAuraTools/Util/UpdateCheck.lua:229: Warning Internal Wa Version does not match Please alert the Author found: 71 expected: 70
[string "=[C]"]: in function `assert'
[string "@DungeonAuraTools/Util/UpdateCheck.lua"]:229: in function `adjustAuras'
[string "@DungeonAuraTools/Util/UpdateCheck.lua"]:96: in function `CheckIfAuraUpdates'
[string "@DungeonAuraTools/Main.lua"]:102: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = false
(*temporary) = "Warning Internal Wa Version does not match Please alert the Author found: 71 expected: 70"

### Reproduction Steps

When games loads

### Saved Variables

14x DungeonAuraTools/Util/UpdateCheck.lua:229: Warning Internal Wa Version does not match Please alert the Author found: 71 expected: 70
[string "=[C]"]: in function `assert'
[string "@DungeonAuraTools/Util/UpdateCheck.lua"]:229: in function `adjustAuras'
[string "@DungeonAuraTools/Util/UpdateCheck.lua"]:96: in function `CheckIfAuraUpdates'
[string "@DungeonAuraTools/Main.lua"]:102: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = false
(*temporary) = "Warning Internal Wa Version does not match Please alert the Author found: 71 expected: 70"

**Comment by Jodsderechte** [comment]
Fixed in the newest version. Thanks for reporting!
