### ISSUE TITLE
Choose a default sound channel for the generated auras

### ISSUE THREAD

**Issue by Jembalolz** [Jods-GH/DungeonAuraTools#143]
### Is your feature request related to a problem? Please describe.

Want to change sound channel to one different from "master" so I can adjust the aura sounds separately without increasing other game sounds. Also, not only do you have to manually change each aura group, but when you do, it triggers the "There are [#] weakauras waiting to be updated" message.

### Describe the solution you'd like

What I think would be a clean solution would be like a dropdown menu on the DungeonAuraTools addon where you could select which is the default sound channel for generated auras. (If this is even possible to automate)

**Comment by Jodsderechte** [comment]
This is added in newest beta and will be in the nex release
