### ISSUE TITLE
release 2.0.9 missing assets

### ISSUE THREAD

**Issue by torkus** [Jods-GH/DungeonAuraTools#144]
### Description

It looks the 2.0.9 release is missing the .zip asset:
![Screenshot at 2024-10-26 09-02-31](https://github.com/user-attachments/assets/bde38dc4-b2ec-4ceb-a728-16cc31642afc)

The build shows that there was an error uploading despite the build step completing successfully:
https://github.com/Jods-GH/DungeonAuraTools/actions/runs/11476437850/job/31936441370#step:5:498

```
Updating GitHub release: https://github.com/Jods-GH/DungeonAuraTools/releases/tag/v2.0.9
Uploading DungeonAuraTools-v2.0.9.zip... Error (404)
{"message":"Not Found","request_id":"5C80:78E97:257337:29066C:6718B96F","documentation_url":"https://docs.github.com/rest/releases/assets#update-a-release-asset"}
Uploading release.json... Success!


Packaging complete.
```

### WeakAuras Version

123

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

123

### Tested with only WeakAuras and DungeonAuraTools

- [ ] Yes
- [X] No

### Lua Error

123

### Reproduction Steps

123

### Saved Variables

123

### Last Good Version

123

### Screenshots

123

**Comment by Jodsderechte** [comment]
Hm not sure what exactly went wrong there but i reran the job and it now has the zip included i'll keep an eye out on the next release and look into it if it still happens. Thanks for reporting!
