### ISSUE TITLE
WA updates not disappear

### ISSUE THREAD

**Issue by lenoirrichelieu** [Jods-GH/DungeonAuraTools#69]
### Description

After the addon sends the updates to WeakAura I can import them, but the updates don't disappear.

### WeakAuras Version

5.2.2

### World of Warcraft Flavor

Retail (Default)

### DungeonAuraTools Version

1.0.9

### Tested with only WeakAuras and DungeonAuraTools

- [ ] Yes
- [X] No

### Lua Error

No errors in bugsack

### Reproduction Steps

1. Open WeakAura
2. use every update available from DungeonAura Tool
3. The updates remain in place

### Saved Variables

Can't upload

### Screenshots

![not disapper WA](https://user-images.githubusercontent.com/94080045/205500385-bdcf8764-8172-43d6-b579-b67af9fc0268.jpg)

**Comment by Jodsderechte** [comment]
currently you need to reload after updating not yet sure why this is the case but that should fix it
